# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExchangerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Exchanger', :git => 'https://github.com/gre4ixin/Exchanger.git', :tag => '1.0.2'
end
